package packages

// Generated by just wire. Do not edit by hand.
import argon "Argon"
import immco "Immco"

Package_Contexts :: struct {
	argon: argon.Context,
	immco: immco.Context,
}

Register_Default_Packages :: proc(registry: ^Registry) {
	Register_Package(registry, "Argon", argon.Install, argon.Begin_Frame, &registry.contexts.argon)
	Register_Package(registry, "Immco", immco.Install, immco.Begin_Frame, &registry.contexts.immco)
}
