param(
    [string]$InputPath = "src/engine/enum/enum.odin",
    [string]$OutputPath = "src/engine/enum/LuaEnumGenerated.odin"
)

$enumNames = Select-String -LiteralPath $InputPath -Pattern '^([A-Za-z_][A-Za-z0-9_]*)\s*::\s*enum(?:\s+[^\s{]+)?\s*\{' |
    ForEach-Object { $_.Matches[0].Groups[1].Value }

if ($enumNames.Count -eq 0) {
    throw "No enum declarations found in $InputPath"
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('package engine_enums')
$lines.Add('')
$lines.Add('// Generated by just wire. Do not edit by hand.')
$lines.Add('Register_Default_Enums :: proc(registry: ^Registry) {')
foreach ($name in $enumNames) {
    $lines.Add("`tRegister_Reflected_Enum(registry, `"$name`", $name)")
}
$lines.Add('}')

$outputDirectory = Split-Path -Parent $OutputPath
if ($outputDirectory) {
    New-Item -ItemType Directory -Force -Path $outputDirectory | Out-Null
}
[System.IO.File]::WriteAllLines($OutputPath, $lines, [System.Text.UTF8Encoding]::new($false))
Write-Host "Generated $OutputPath with $($enumNames.Count) enums"
